name: 'Render Quarto project'
author: 'Carlos Scheidegger'
description: 'This action will render an existing quarto project'
inputs:
  to:
    description: 'Format to render output. Use "all" to generate all outputs, when eg rendering a book in HTML and PDF'
    required: false
  path:
    description: 'Subdirectory containing the quarto project to be rendered'
    required: false
    default: "."
runs:
  using: 'composite'
  steps: 
    - name: 'Render'
      env:
        QUARTO_PRINT_STACK: true
      run: |
        if [ "${{ inputs.to }}" == "" ]; then
          quarto render ${{ inputs.path }}
        else
          quarto render ${{ inputs.path }} --to ${{ inputs.to }}
        fi
        if [ -f "_book" ]; then
          echo "QUARTO_OUTPUT=_book" >> $GITHUB_ENV
        elif [ -f "_site" ]; then
          echo "QUARTO_OUTPUT=_site" >> $GITHUB_ENV
        fi
      shell: bash
